#!/bin/bash

clear
t=0
cols=$(tput cols)
rows=$(tput lines)
amplitude=$((rows / 4))
frequency=0.1
speed=0.02

while true; do
    clear
    for ((x = 0; x < cols; x++)); do
        y=$(awk -v x="$x" -v t="$t" -v a="$amplitude" -v f="$frequency" 'BEGIN { 
            y = int(a * sin(f * x + t)); 
            print y 
        }')
        row=$(( (rows / 2) + y ))
        tput cup "$row" "$x"
        printf "~"
    done
    t=$(awk -v t="$t" -v s="$speed" 'BEGIN { print t + s }')
    sleep 0.1
done
